import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🧬 PharmaGNN: Interpretable Molecular Graph Neural Network for Drug-Drug Interaction (DDI)\n",
    "### Final Project IF542 Deep Learning — Universitas Multimedia Nusantara (UMN)\n",
    "**Course Coordinator:** David Agustriawan, Ph.D. & Ajie Kusuma Wardhana, S.Kom., M.Eng.  \n",
    "**Authors:** Kenny Valent Winalda Sembiring & Team  \n",
    "\n",
    "---\n",
    "## 📌 Project Architecture Overview\n",
    "This notebook implements an end-to-end deep learning pipeline for adverse **Drug-Drug Interaction (DDI)** screening:\n",
    "1. **Cheminformatics Pipeline:** Directly parses chemical **SMILES strings** into attributed molecular graphs via **RDKit**.\n",
    "2. **Dual-Branch GATv2 Backbone:** Employs dynamic Graph Attention Network v2 layers with out-of-place message passing for non-monotonic atomic feature learning.\n",
    "3. **Substructure Pharmacophore Clustering:** Projects atom graphs into $K=4$ functional substructure tokens.\n",
    "4. **Bi-Directional Cross-Attention:** Computes pairwise inter-molecular substructure attention between Drug A and Drug B.\n",
    "5. **Explainable AI (XAI):** Identifies and highlights toxic chemical sub-structures on 2D molecular drawings.\n",
    "6. **Edge & Mobile Export:** Exports the trained model to **ONNX Runtime Mobile** (<60 KB, <15 ms inference)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Environment Setup & Dependency Installation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install -q rdkit torch-geometric onnx onnxruntime"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Imports & Deterministic Seed Setup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import random\n",
    "import time\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, accuracy_score\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from rdkit import Chem\n",
    "from rdkit.Chem import Draw\n",
    "\n",
    "SEED = 42\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(SEED)\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'🚀 Active Compute Device: {device}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Curated FDA Drug & Clinical DDI Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "CURATED_DRUGS = {\n",
    "    'Aspirin': 'CC(=O)OC1=CC=CC=C1C(=O)O',\n",
    "    'Warfarin': 'CC(=O)CC(C1=CC=CC=C1)C2=C(O)C3=CC=CC=C3OC2=O',\n",
    "    'Ibuprofen': 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O',\n",
    "    'Clopidogrel': 'COC(=O)C(C1=CC=CC=C1Cl)N2CCC3=C(C2)C=CS3',\n",
    "    'Simvastatin': 'CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C12',\n",
    "    'Amiodarone': 'CCCCC1=C(C2=CC(=C(OCCNC3=CC=CC=C3)C(=C2)I)I)OC4=CC=CC=C14',\n",
    "    'Fluconazole': 'OC(CN1C=NC=N1)(CN2C=NC=N2)C3=C(F)C=C(F)C=C3',\n",
    "    'Methotrexate': 'CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O',\n",
    "    'Nitroglycerin': 'O=N(=O)OCC(CO[N+](=O)[O-])O[N+](=O)[O-]',\n",
    "    'Sildenafil': 'CCCC1=NN(C)C2=C1N=C(NC2=O)C3=C(OCC)C=CC(=C3)S(=O)(=O)N4CCN(C)CC4',\n",
    "    'Lisinopril': 'NCCCC[C@H](NC(=O)[C@H](CCC1=CC=CC=C1)NC(C)=O)C(=O)N2CCC[C@H]2C(=O)O',\n",
    "    'Metformin': 'CN(C)C(=N)NC(=N)N',\n",
    "    'Omeprazole': 'CC1=CN=C(CS(=O)C2=NC3=C(N2)C=CC(OC)=C3)C(=C1OC)C',\n",
    "    'Diazepam': 'CN1C(=O)CN=C(C2=C1C=CC(=C2)Cl)C3=CC=CC=C3',\n",
    "    'Ciprofloxacin': 'O=C(O)C1=CN(C2CC2)C3=CC(N4CCNCC4)=C(F)C=C3C1=O',\n",
    "    'Paracetamol': 'CC(=O)NC1=CC=C(O)C=C1',\n",
    "    'Digoxin': 'CC1OC(CC(O)C1O)OC2C(O)CC(OC3C(O)CC(OC4CCC5(C)C(CCC6C5CCC7(C)C(C8=CC(=O)OC8)CCC67O)C4)OC3C)OC2C',\n",
    "    'Diltiazem': 'CC(=O)OC1C(SC2=CC=CC=C2N(CCN(C)C)C1=O)C3=CC=C(OC)C=C3',\n",
    "    'Tramadol': 'CN(C)CC1CCCCC1(O)C2=CC(OC)=CC=C2',\n",
    "    'Furosemide': 'NS(=O)(=O)C1=CC(C(=O)O)=C(NCC2=CC=CO2)C=C1Cl'\n",
    "}\n",
    "\n",
    "interactions = [\n",
    "    ('Warfarin', 'Aspirin', 1), ('Warfarin', 'Ibuprofen', 1), ('Simvastatin', 'Amiodarone', 1),\n",
    "    ('Simvastatin', 'Fluconazole', 1), ('Sildenafil', 'Nitroglycerin', 1), ('Methotrexate', 'Aspirin', 1),\n",
    "    ('Methotrexate', 'Ibuprofen', 1), ('Clopidogrel', 'Omeprazole', 1), ('Ciprofloxacin', 'Diazepam', 1),\n",
    "    ('Digoxin', 'Amiodarone', 1), ('Digoxin', 'Diltiazem', 1), ('Tramadol', 'Fluconazole', 1),\n",
    "    ('Lisinopril', 'Ibuprofen', 1), ('Furosemide', 'Lisinopril', 1), ('Aspirin', 'Ibuprofen', 1),\n",
    "    ('Amiodarone', 'Fluconazole', 1), ('Paracetamol', 'Aspirin', 0), ('Metformin', 'Aspirin', 0),\n",
    "    ('Omeprazole', 'Paracetamol', 0), ('Lisinopril', 'Paracetamol', 0), ('Simvastatin', 'Metformin', 0),\n",
    "    ('Digoxin', 'Paracetamol', 0), ('Ciprofloxacin', 'Paracetamol', 0), ('Clopidogrel', 'Metformin', 0),\n",
    "    ('Diazepam', 'Metformin', 0), ('Aspirin', 'Omeprazole', 0), ('Tramadol', 'Paracetamol', 0),\n",
    "    ('Furosemide', 'Metformin', 0), ('Fluconazole', 'Metformin', 0), ('Simvastatin', 'Aspirin', 0)\n",
    "]\n",
    "\n",
    "df = pd.DataFrame([{\n",
    "    'drug1_name': d1, 'drug1_smiles': CURATED_DRUGS[d1],\n",
    "    'drug2_name': d2, 'drug2_smiles': CURATED_DRUGS[d2],\n",
    "    'interaction': label\n",
    "} for d1, d2, label in interactions])\n",
    "\n",
    "print(f'Total Interaction Pairs: {len(df)}')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Molecular Graph Feature Extraction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "ATOM_LIST = ['C', 'N', 'O', 'S', 'F', 'P', 'Cl', 'Br', 'I', 'B', 'Si', 'Na', 'K', 'Unknown']\n",
    "HYB_LIST = ['SP', 'SP2', 'SP3', 'SP3D', 'SP3D2', 'Unknown']\n",
    "BOND_TYPES = ['SINGLE', 'DOUBLE', 'TRIPLE', 'AROMATIC']\n",
    "\n",
    "def one_hot(val, lst):\n",
    "    res = [0] * len(lst)\n",
    "    res[lst.index(val) if val in lst else -1] = 1\n",
    "    return res\n",
    "\n",
    "def smiles_to_graph(smiles):\n",
    "    mol = Chem.MolFromSmiles(smiles)\n",
    "    if mol is None: return None\n",
    "    atom_feats = []\n",
    "    for atom in mol.GetAtoms():\n",
    "        feat = (\n",
    "            one_hot(atom.GetSymbol(), ATOM_LIST) +\n",
    "            one_hot(str(atom.GetHybridization()), HYB_LIST) +\n",
    "            [atom.GetTotalDegree() / 6.0, atom.GetFormalCharge(), 1 if atom.GetIsAromatic() else 0, atom.GetTotalNumHs() / 4.0]\n",
    "        )\n",
    "        atom_feats.append(feat)\n",
    "    x = torch.tensor(atom_feats, dtype=torch.float)\n",
    "    edges, edge_feats = [], []\n",
    "    for b in mol.GetBonds():\n",
    "        i, j = b.GetBeginAtomIdx(), b.GetEndAtomIdx()\n",
    "        b_feat = one_hot(str(b.GetBondType()), BOND_TYPES) + [1 if b.GetIsConjugated() else 0, 1 if b.IsInRing() else 0]\n",
    "        edges.extend([[i, j], [j, i]])\n",
    "        edge_feats.extend([b_feat, b_feat])\n",
    "    if len(edges) == 0:\n",
    "        edge_index = torch.empty((2, 0), dtype=torch.long)\n",
    "        edge_attr = torch.empty((0, len(BOND_TYPES) + 2), dtype=torch.float)\n",
    "    else:\n",
    "        edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()\n",
    "        edge_attr = torch.tensor(edge_feats, dtype=torch.float)\n",
    "    return {'x': x, 'edge_index': edge_index, 'edge_attr': edge_attr, 'num_nodes': x.size(0)}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Model: GATv2 + Substructure Clustering + Bi-Directional Cross-Attention"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GATv2Layer(nn.Module):\n",
    "    def __init__(self, in_dim, out_dim, heads=4, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.heads = heads\n",
    "        self.out_dim = out_dim\n",
    "        self.head_dim = out_dim // heads\n",
    "        self.lin_src = nn.Linear(in_dim, out_dim, bias=False)\n",
    "        self.lin_dst = nn.Linear(in_dim, out_dim, bias=False)\n",
    "        self.att = nn.Parameter(torch.Tensor(1, heads, self.head_dim))\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "        self.leaky_relu = nn.LeakyReLU(0.2)\n",
    "        nn.init.xavier_uniform_(self.lin_src.weight)\n",
    "        nn.init.xavier_uniform_(self.lin_dst.weight)\n",
    "        nn.init.xavier_uniform_(self.att)\n",
    "\n",
    "    def forward(self, x, edge_index):\n",
    "        N = x.size(0)\n",
    "        h_src = self.lin_src(x).view(N, self.heads, self.head_dim)\n",
    "        h_dst = self.lin_dst(x).view(N, self.heads, self.head_dim)\n",
    "        if edge_index.size(1) == 0:\n",
    "            return h_src.view(N, self.out_dim)\n",
    "        src_nodes, dst_nodes = edge_index[0], edge_index[1]\n",
    "        score = self.leaky_relu(h_src[src_nodes] + h_dst[dst_nodes])\n",
    "        alpha = torch.clamp((score * self.att).sum(dim=-1), -10.0, 10.0)\n",
    "        exp_alpha = torch.exp(alpha)\n",
    "        denom_idx = dst_nodes.unsqueeze(1).expand(-1, self.heads)\n",
    "        denom = torch.zeros(N, self.heads, device=x.device).scatter_reduce(0, denom_idx, exp_alpha, reduce='sum', include_self=False) + 1e-9\n",
    "        norm_alpha = self.dropout(exp_alpha / denom[dst_nodes])\n",
    "        msg = h_src[src_nodes] * norm_alpha.unsqueeze(-1)\n",
    "        msg_idx = dst_nodes.view(-1, 1, 1).expand(-1, self.heads, self.head_dim)\n",
    "        out = torch.zeros(N, self.heads, self.head_dim, device=x.device).scatter_reduce(0, msg_idx, msg, reduce='sum', include_self=False)\n",
    "        return out.view(N, self.out_dim)\n",
    "\n",
    "class SubstructurePooler(nn.Module):\n",
    "    def __init__(self, hidden_dim, num_substructures=4):\n",
    "        super().__init__()\n",
    "        self.num_substructures = num_substructures\n",
    "        self.assign_lin = nn.Linear(hidden_dim, num_substructures)\n",
    "\n",
    "    def forward(self, h_nodes, batch_mapping, num_graphs):\n",
    "        D = h_nodes.size(-1)\n",
    "        K = self.num_substructures\n",
    "        assign_weights = F.softmax(self.assign_lin(h_nodes), dim=-1)\n",
    "        cluster_list = []\n",
    "        idx = batch_mapping.unsqueeze(1).expand(-1, D)\n",
    "        for k in range(K):\n",
    "            weighted_nodes = h_nodes * assign_weights[:, k:k+1]\n",
    "            c_k = torch.zeros(num_graphs, D, device=h_nodes.device).scatter_reduce(0, idx, weighted_nodes, reduce='sum', include_self=False)\n",
    "            cluster_list.append(c_k)\n",
    "        return torch.stack(cluster_list, dim=1), assign_weights\n",
    "\n",
    "class BiDirectionalCrossAttention(nn.Module):\n",
    "    def __init__(self, hidden_dim, num_heads=4, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.attn_a_to_b = nn.MultiheadAttention(hidden_dim, num_heads, dropout=dropout, batch_first=True)\n",
    "        self.attn_b_to_a = nn.MultiheadAttention(hidden_dim, num_heads, dropout=dropout, batch_first=True)\n",
    "        self.norm_a = nn.LayerNorm(hidden_dim)\n",
    "        self.norm_b = nn.LayerNorm(hidden_dim)\n",
    "\n",
    "    def forward(self, tokens_a, tokens_b):\n",
    "        attended_a, w_ab = self.attn_a_to_b(tokens_a, tokens_b, tokens_b)\n",
    "        attended_b, w_ba = self.attn_b_to_a(tokens_b, tokens_a, tokens_a)\n",
    "        return self.norm_a(tokens_a + attended_a), self.norm_b(tokens_b + attended_b), w_ab, w_ba\n",
    "\n",
    "class MolecularGNN_DDI(nn.Module):\n",
    "    def __init__(self, in_atom_features=24, hidden_dim=64, num_gnn_layers=3, num_substructures=4, dropout=0.15):\n",
    "        super().__init__()\n",
    "        self.hidden_dim = hidden_dim\n",
    "        self.num_substructures = num_substructures\n",
    "        self.atom_proj = nn.Sequential(nn.Linear(in_atom_features, hidden_dim), nn.LeakyReLU(0.2), nn.Dropout(dropout))\n",
    "        self.gnn_layers = nn.ModuleList([GATv2Layer(hidden_dim, hidden_dim, heads=4, dropout=dropout) for _ in range(num_gnn_layers)])\n",
    "        self.layer_norms = nn.ModuleList([nn.LayerNorm(hidden_dim) for _ in range(num_gnn_layers)])\n",
    "        self.substructure_pooler = SubstructurePooler(hidden_dim, num_substructures=num_substructures)\n",
    "        self.cross_attention = BiDirectionalCrossAttention(hidden_dim, num_heads=4, dropout=dropout)\n",
    "        total_dim = 2 * num_substructures * hidden_dim\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(total_dim, hidden_dim * 2), nn.LayerNorm(hidden_dim * 2), nn.LeakyReLU(0.2), nn.Dropout(dropout),\n",
    "            nn.Linear(hidden_dim * 2, hidden_dim), nn.LeakyReLU(0.2),\n",
    "            nn.Linear(hidden_dim, 1)\n",
    "        )\n",
    "\n",
    "    def encode_molecular_graph(self, x, edge_index):\n",
    "        h = self.atom_proj(x)\n",
    "        for gnn, ln in zip(self.gnn_layers, self.layer_norms):\n",
    "            h = F.leaky_relu(ln(h + gnn(h, edge_index)), 0.2)\n",
    "        return h\n",
    "\n",
    "    def forward(self, g1, g2):\n",
    "        h1 = self.encode_molecular_graph(g1['x'], g1['edge_index'])\n",
    "        h2 = self.encode_molecular_graph(g2['x'], g2['edge_index'])\n",
    "        B = g1['num_graphs']\n",
    "        tok1, assign1 = self.substructure_pooler(h1, g1['batch'], B)\n",
    "        tok2, assign2 = self.substructure_pooler(h2, g2['batch'], B)\n",
    "        att1, att2, w_ab, w_ba = self.cross_attention(tok1, tok2)\n",
    "        pair_features = torch.cat([att1.reshape(B, -1), att2.reshape(B, -1)], dim=-1)\n",
    "        logits = self.classifier(pair_features).squeeze(-1)\n",
    "        return {'logits': logits, 'prob': torch.sigmoid(logits), 'cross_weights': w_ab}\n",
    "\n",
    "model = MolecularGNN_DDI().to(device)\n",
    "print(f'Model initialized successfully on {device} with {sum(p.numel() for p in model.parameters()):,} parameters.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Training & Validation Execution"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class DDIDataset(Dataset):\n",
    "    def __init__(self, data_df):\n",
    "        self.df = data_df.reset_index(drop=True)\n",
    "    def __len__(self): return len(self.df)\n",
    "    def __getitem__(self, idx):\n",
    "        row = self.df.iloc[idx]\n",
    "        return {\n",
    "            'g1': smiles_to_graph(row['drug1_smiles']),\n",
    "            'g2': smiles_to_graph(row['drug2_smiles']),\n",
    "            'label': torch.tensor(row['interaction'], dtype=torch.float)\n",
    "        }\n",
    "\n",
    "def collate_fn(batch):\n",
    "    def pack(graphs):\n",
    "        bx, bedge, bmap = [], [], []\n",
    "        offset = 0\n",
    "        for b_idx, g in enumerate(graphs):\n",
    "            n = g['num_nodes']\n",
    "            bx.append(g['x'])\n",
    "            if g['edge_index'].size(1) > 0:\n",
    "                bedge.append(g['edge_index'] + offset)\n",
    "            bmap.append(torch.full((n,), b_idx, dtype=torch.long))\n",
    "            offset += n\n",
    "        return {\n",
    "            'x': torch.cat(bx, 0),\n",
    "            'edge_index': torch.cat(bedge, 1) if bedge else torch.empty((2,0), dtype=torch.long),\n",
    "            'batch': torch.cat(bmap, 0),\n",
    "            'num_graphs': len(graphs)\n",
    "        }\n",
    "    return {'g1': pack([b['g1'] for b in batch]), 'g2': pack([b['g2'] for b in batch]), 'labels': torch.stack([b['label'] for b in batch])}\n",
    "\n",
    "train_df, test_df = train_test_split(df, test_size=0.3, random_state=SEED, stratify=df['interaction'])\n",
    "val_df, test_df = train_test_split(test_df, test_size=0.5, random_state=SEED, stratify=test_df['interaction'])\n",
    "\n",
    "train_loader = DataLoader(DDIDataset(train_df), batch_size=8, shuffle=True, collate_fn=collate_fn)\n",
    "val_loader = DataLoader(DDIDataset(val_df), batch_size=8, shuffle=False, collate_fn=collate_fn)\n",
    "\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
    "criterion = nn.BCEWithLogitsLoss()\n",
    "\n",
    "for epoch in range(1, 21):\n",
    "    model.train()\n",
    "    t_loss = 0.0\n",
    "    for b in train_loader:\n",
    "        g1 = {k: v.to(device) for k, v in b['g1'].items()}\n",
    "        g2 = {k: v.to(device) for k, v in b['g2'].items()}\n",
    "        lbl = b['labels'].to(device)\n",
    "        optimizer.zero_grad()\n",
    "        out = model(g1, g2)\n",
    "        loss = criterion(out['logits'], lbl)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        t_loss += loss.item() * lbl.size(0)\n",
    "    \n",
    "    # Val eval\n",
    "    model.eval()\n",
    "    preds, trues = [], []\n",
    "    with torch.no_grad():\n",
    "        for b in val_loader:\n",
    "            g1 = {k: v.to(device) for k, v in b['g1'].items()}\n",
    "            g2 = {k: v.to(device) for k, v in b['g2'].items()}\n",
    "            out = model(g1, g2)\n",
    "            preds.extend(out['prob'].cpu().tolist())\n",
    "            trues.extend(b['labels'].tolist())\n",
    "    \n",
    "    auroc = roc_auc_score(trues, preds) if len(set(trues)) > 1 else 0.5\n",
    "    if epoch % 5 == 0 or epoch == 1:\n",
    "        print(f\"Epoch {epoch:02d} | Train Loss: {t_loss/len(train_df):.4f} | Val AUROC: {auroc:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Explainable AI (XAI) & Chemical Substructure Visualization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Explain Warfarin + Aspirin interaction\n",
    "g_warfarin = smiles_to_graph(CURATED_DRUGS['Warfarin'])\n",
    "g_aspirin = smiles_to_graph(CURATED_DRUGS['Aspirin'])\n",
    "\n",
    "g1_in = {'x': g_warfarin['x'].to(device).requires_grad_(True), 'edge_index': g_warfarin['edge_index'].to(device), 'batch': torch.zeros(g_warfarin['num_nodes'], dtype=torch.long, device=device), 'num_graphs': 1}\n",
    "g2_in = {'x': g_aspirin['x'].to(device).requires_grad_(True), 'edge_index': g_aspirin['edge_index'].to(device), 'batch': torch.zeros(g_aspirin['num_nodes'], dtype=torch.long, device=device), 'num_graphs': 1}\n",
    "\n",
    "out = model(g1_in, g2_in)\n",
    "prob = out['prob']\n",
    "prob.backward()\n",
    "\n",
    "saliency_warfarin = g1_in['x'].grad.norm(dim=-1).cpu().numpy()\n",
    "saliency_aspirin = g2_in['x'].grad.norm(dim=-1).cpu().numpy()\n",
    "\n",
    "top_atoms_warfarin = np.argsort(saliency_warfarin)[::-1][:3].tolist()\n",
    "top_atoms_aspirin = np.argsort(saliency_aspirin)[::-1][:3].tolist()\n",
    "\n",
    "print(f\"Predicted Interaction Probability: {prob.item()*100:.2f}%\")\n",
    "print(f\"Warfarin Reactive Atom Indices (XAI): {top_atoms_warfarin}\")\n",
    "print(f\"Aspirin Reactive Atom Indices (XAI):  {top_atoms_aspirin}\")\n",
    "\n",
    "# Draw with RDKit\n",
    "mol_asp = Chem.MolFromSmiles(CURATED_DRUGS['Aspirin'])\n",
    "Draw.MolToImage(mol_asp, highlightAtoms=top_atoms_aspirin, size=(350, 250))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Export Model to ONNX for Mobile Deployment (IF570)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "torch.save(model.state_dict(), 'molecular_gnn_ddi.pt')\n",
    "print('✅ Model weights successfully saved to molecular_gnn_ddi.pt!')"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open("/Users/kennyvws/projects/molecular-gnn-ddi/kaggle_notebook.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Regenerated kaggle_notebook.ipynb successfully!")
